#!/usr/bin/env python3
"""Generate the Loki interface C headers from the YAML descriptors.

Inputs:
    interface/gatt.yaml   — GATT service / characteristics (UUIDs, naming caps).
    interface/coap.yaml   — CoAP port, resource paths, direction enum.

Outputs (overwritten in-place when content changes):
    interface/generated/loki_gatt.h
    interface/generated/loki_coap.h

Failure mode policy:
    This script is invoked from CMake at every build. It MUST NOT fail the
    build when prerequisites are missing (e.g. PyYAML not installed, Python
    too old). In those cases it prints a warning to stderr, leaves the
    existing generated headers untouched, and exits 0. The build then uses
    the previously generated headers as-is.

Hard failures (exit non-zero) are reserved for inputs that ARE present but
malformed — those indicate a bug in the YAML the developer must fix.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

MIN_PYTHON = (3, 8)


# ----------------------------------------------------------------------------
# Failure-mode helpers
# ----------------------------------------------------------------------------

def warn(msg: str) -> None:
    print(f"gen_descriptors.py: warning: {msg}", file=sys.stderr)


def warn_skip(reason: str) -> "None":
    warn(reason)
    warn("skipping regeneration; pre-existing generated headers retained.")
    sys.exit(0)


def fatal(msg: str) -> "None":
    print(f"gen_descriptors.py: error: {msg}", file=sys.stderr)
    sys.exit(1)


def check_python() -> None:
    if sys.version_info < MIN_PYTHON:
        have = ".".join(str(x) for x in sys.version_info[:3])
        need = ".".join(str(x) for x in MIN_PYTHON)
        warn_skip(f"requires Python {need}+; have {have}")


def import_yaml():
    try:
        import yaml  # type: ignore
        return yaml
    except ImportError:
        warn_skip("PyYAML is not installed (try `pip install pyyaml`)")


# ----------------------------------------------------------------------------
# UUID helpers
# ----------------------------------------------------------------------------

_UUID_RE = re.compile(
    r"^([0-9a-f]{8})-([0-9a-f]{4})-([0-9a-f]{4})-([0-9a-f]{4})-([0-9a-f]{12})$"
)


def split_uuid_to_bt_encode(uuid: str) -> str:
    """Render `fcbd0001-5e25-4387-99b7-53a5495a0c35` as the five hex args that
    BT_UUID_128_ENCODE expects."""
    m = _UUID_RE.match(uuid.lower())
    if not m:
        fatal(f"invalid UUID syntax: {uuid!r}")
    return ", ".join(f"0x{g}" for g in m.groups())


# ----------------------------------------------------------------------------
# Renderers
# ----------------------------------------------------------------------------

GENERATED_BANNER = (
    "/* SPDX-License-Identifier: LicenseRef-Nordic-5-Clause */\n"
    "/* AUTO-GENERATED by tools/gen_descriptors.py from {src}.\n"
    " * Do not edit by hand — your changes will be overwritten on the next build.\n"
    " * Edit the YAML source instead. */\n"
)


def render_gatt(doc: dict) -> str:
    svc = doc["service"]
    prefix = svc["c_prefix"]
    chars = doc["characteristics"]
    nm = doc.get("ble_name", {})

    lines: list[str] = []
    lines.append(GENERATED_BANNER.format(src="interface/gatt.yaml"))
    lines.append("#ifndef LOKI_GATT_GENERATED_H")
    lines.append("#define LOKI_GATT_GENERATED_H")
    lines.append("")
    lines.append("#include <zephyr/bluetooth/uuid.h>")
    lines.append("")

    if nm:
        lines.append("/* BLE naming constraints. */")
        if "default_prefix" in nm:
            lines.append(f'#define DEFAULT_NAME_PREFIX  "{nm["default_prefix"]}"')
        if "max_short" in nm:
            lines.append(f"#define MAX_LEN_BLE_NAME     {nm['max_short']}")
        if "max_full" in nm:
            lines.append(f"#define MAX_LEN_FULL_NAME    {nm['max_full']}")
        lines.append("")

    lines.append(f"/* {svc['name']} primary service. */")
    lines.append(f"#define {prefix}_SERVICE_UUID_VAL \\")
    lines.append(f"    BT_UUID_128_ENCODE({split_uuid_to_bt_encode(svc['uuid'])})")
    lines.append(f"#define {prefix}_SERVICE_UUID \\")
    lines.append(f"    BT_UUID_DECLARE_128({prefix}_SERVICE_UUID_VAL)")
    lines.append("")

    for ch in chars:
        sym = ch["c_symbol"]
        macro_val = f"{prefix}_{sym}_UUID_VAL"
        macro_uuid = f"{prefix}_{sym}_UUID"
        lines.append(f"/* {ch['name']} characteristic. */")
        lines.append(f"#define {macro_val} \\")
        lines.append(
            f"    BT_UUID_128_ENCODE({split_uuid_to_bt_encode(ch['uuid'])})"
        )
        lines.append(f"#define {macro_uuid} \\")
        lines.append(f"    BT_UUID_DECLARE_128({macro_val})")
        lines.append("")

    lines.append("#endif /* LOKI_GATT_GENERATED_H */")
    lines.append("")
    return "\n".join(lines)


def render_coap(doc: dict) -> str:
    lines: list[str] = []
    lines.append(GENERATED_BANNER.format(src="interface/coap.yaml"))
    lines.append("#ifndef LOKI_COAP_GENERATED_H")
    lines.append("#define LOKI_COAP_GENERATED_H")
    lines.append("")
    lines.append(f"#define COAP_PORT {doc['port']}")
    lines.append("")

    # Resource URI paths. Align values for readability.
    res = doc.get("resources", [])
    if res:
        width = max(len(r["c_symbol"]) for r in res)
        lines.append("/* CoAP resource URI paths. */")
        for r in res:
            sym = r["c_symbol"]
            lines.append(f'#define {sym:<{width}} "{r["path"]}"')
        lines.append("")

    enum = doc.get("direction_enum")
    if enum:
        lines.append(f"/* Direction command bytes — {enum['c_name']}. */")
        lines.append(f"enum {enum['c_name']} {{")
        vals = enum["values"]
        for i, v in enumerate(vals):
            tail = "," if i < len(vals) - 1 else ""
            lines.append(f"\t{v['c_symbol']} = {v['value']}{tail}")
        lines.append("};")
        lines.append("")

    lines.append("#endif /* LOKI_COAP_GENERATED_H */")
    lines.append("")
    return "\n".join(lines)


# ----------------------------------------------------------------------------
# File writer
# ----------------------------------------------------------------------------

def write_if_changed(path: Path, content: str) -> bool:
    """Write `content` to `path` only if it differs. Returns True if written.

    Keeps mtimes stable so CMake doesn't think the headers changed unless
    they really did — important because the generated headers feed back
    into the C build as dependencies."""
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


# ----------------------------------------------------------------------------
# Entrypoint
# ----------------------------------------------------------------------------

def main() -> None:
    check_python()
    yaml = import_yaml()

    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--gatt", type=Path, required=True,
                    help="path to interface/gatt.yaml")
    ap.add_argument("--coap", type=Path, required=True,
                    help="path to interface/coap.yaml")
    ap.add_argument("--out-dir", type=Path, required=True,
                    help="output directory for the generated headers")
    args = ap.parse_args()

    for p in (args.gatt, args.coap):
        if not p.is_file():
            fatal(f"input not found: {p}")

    try:
        gatt_doc = yaml.safe_load(args.gatt.read_text(encoding="utf-8"))
        coap_doc = yaml.safe_load(args.coap.read_text(encoding="utf-8"))
    except yaml.YAMLError as e:  # type: ignore[attr-defined]
        fatal(f"YAML parse error: {e}")

    if not isinstance(gatt_doc, dict):
        fatal("interface/gatt.yaml must have a mapping (dict) at the document root")
    if not isinstance(coap_doc, dict):
        fatal("interface/coap.yaml must have a mapping (dict) at the document root")

    gatt_header = render_gatt(gatt_doc)
    coap_header = render_coap(coap_doc)

    args.out_dir.mkdir(parents=True, exist_ok=True)
    wrote_gatt = write_if_changed(args.out_dir / "loki_gatt.h", gatt_header)
    wrote_coap = write_if_changed(args.out_dir / "loki_coap.h", coap_header)

    if wrote_gatt or wrote_coap:
        names = []
        if wrote_gatt:
            names.append("loki_gatt.h")
        if wrote_coap:
            names.append("loki_coap.h")
        print(
            "gen_descriptors.py: regenerated "
            + ", ".join(names)
            + f" in {args.out_dir}"
        )


if __name__ == "__main__":
    main()
